INSERT INTO SocialNetwork.users (user_id, username, email, password_hash, bio, avatar_url)
VALUES
(1, 'alice', 'alice@example.com', 'hash123alice', 'Фотограф и блогер.', 'https://example.com/avatars/alice.png'),
(2, 'bob', 'bob@example.com', 'hash123bob', 'Геймер и фанат киберспорта.', 'https://example.com/avatars/bob.png'),
(3, 'charlie', 'charlie@example.com', 'hash123charlie', 'Путешественник по миру.', 'https://example.com/avatars/charlie.png'),
(4, 'diana', 'diana@example.com', 'hash123diana', 'Люблю музыку и поэзию.', 'https://example.com/avatars/diana.png'),
(5, 'eva', 'eva@example.com', 'hash123eva', 'Разработчик Python.', 'https://example.com/avatars/eva.png'),
(6, 'frank', 'frank@example.com', 'hash123frank', 'Бариста и фанат латте.', 'https://example.com/avatars/frank.png'),
(7, 'grace', 'grace@example.com', 'hash123grace', 'UX-дизайнер.', 'https://example.com/avatars/grace.png'),
(8, 'hank', 'hank@example.com', 'hash123hank', 'Бегун-марафонец.', 'https://example.com/avatars/hank.png'),
(9, 'irene', 'irene@example.com', 'hash123irene', 'Книжный червь.', 'https://example.com/avatars/irene.png'),
(10, 'jack', 'jack@example.com', 'hash123jack', 'Фанат настольных игр.', 'https://example.com/avatars/jack.png'),
(11, 'kate', 'kate@example.com', 'hash123kate', 'Фотограф дикой природы.', 'https://example.com/avatars/kate.png'),
(12, 'leo', 'leo@example.com', 'hash123leo', 'Люблю кодить по ночам.', 'https://example.com/avatars/leo.png'),
(13, 'mia', 'mia@example.com', 'hash123mia', 'Танцую с детства.', 'https://example.com/avatars/mia.png'),
(14, 'nate', 'nate@example.com', 'hash123nate', 'Фанат sci-fi и комиксов.', 'https://example.com/avatars/nate.png'),
(15, 'olivia', 'olivia@example.com', 'hash123olivia', 'Скетчинг и кофе.', 'https://example.com/avatars/olivia.png'),
(16, 'peter', 'peter@example.com', 'hash123peter', 'IT-консультант.', 'https://example.com/avatars/peter.png'),
(17, 'quinn', 'quinn@example.com', 'hash123quinn', 'Инфлюенсер в TikTok.', 'https://example.com/avatars/quinn.png'),
(18, 'rachel', 'rachel@example.com', 'hash123rachel', 'Преподаватель английского.', 'https://example.com/avatars/rachel.png'),
(19, 'sam', 'sam@example.com', 'hash123sam', 'Инди-разработчик игр.', 'https://example.com/avatars/sam.png'),
(20, 'tina', 'tina@example.com', 'hash123tina', 'Кулинарный блогер.', 'https://example.com/avatars/tina.png'),
(21, 'ursula', 'ursula@example.com', 'hash123ursula', 'Фанат хорроров.', 'https://example.com/avatars/ursula.png'),
(22, 'victor', 'victor@example.com', 'hash123victor', 'Спортсмен и тренер.', 'https://example.com/avatars/victor.png'),
(23, 'wanda', 'wanda@example.com', 'hash123wanda', 'Геймерша и стример.', 'https://example.com/avatars/wanda.png'),
(24, 'xander', 'xander@example.com', 'hash123xander', 'Инженер по данным.', 'https://example.com/avatars/xander.png'),
(25, 'yasmin', 'yasmin@example.com', 'hash123yasmin', 'Пишу стихи.', 'https://example.com/avatars/yasmin.png'),
(26, 'zack', 'zack@example.com', 'hash123zack', 'Фанат Marvel.', 'https://example.com/avatars/zack.png'),
(27, 'bella', 'bella@example.com', 'hash123bella', 'Кино и театр.', 'https://example.com/avatars/bella.png'),
(28, 'ethan', 'ethan@example.com', 'hash123ethan', 'UX-аналитик.', 'https://example.com/avatars/ethan.png'),
(29, 'lucy', 'lucy@example.com', 'hash123lucy', 'Космос — моя страсть.', 'https://example.com/avatars/lucy.png'),
(30, 'max', 'max@example.com', 'hash123max', 'Пишу музыку.', 'https://example.com/avatars/max.png');
